import { loadTestCase } from "../testUtils";
import parseStoryList from "./parseStoryList";

describe("parseStoryList", function () {
  it("should parse main page", async function () {
    const fragment = await loadTestCase("01-main-page.html");
    const parsed = await parseStoryList(fragment);

    expect(parsed).toBeUndefined();
  });

  it("should parse story page", async function () {
    const fragment = await loadTestCase("02-dreaming-of-sunshine.html");
    const parsed = await parseStoryList(fragment);

    expect(parsed).toBeUndefined();
  });

  it("should parse follows list", async function () {
    const fragment = await loadTestCase("05-alerts.html");
    const parsed = await parseStoryList(fragment);

    expect(parsed).toBeUndefined();
  });

  it("should parse crossover story list", async function () {
    const fragment = await loadTestCase("06-hp-naruto-crossovers.html");
    const parsed = await parseStoryList(fragment);

    expect(parsed).toStrictEqual([
      {
        id: 11634921,
        title: "Itachi, Is That A Baby?",
        author: {
          id: 7288663,
          name: "SpoonandJohn",
        },
        description:
          'Petunia performs a bit of accidental magic. It says something about her parenting that Uchiha Itachi is considered a better prospect for raising a child. Young Hari is raised by one of the most infamous nukenin of all time and a cadre of "Uncles" whose cumulative effect is very . . . prominent. And someone had the bright idea to bring him back to England. Merlin help them all.',
        imageUrl: undefined,
        favorites: 11183,
        follows: 11652,
        reviews: 8029,
        genre: ["Humor", "Adventure"],
        characters: [["Harry P."], ["Albus D."], ["Itachi U."]],
        language: "English",
        published: new Date("2015-11-26T05:56:35Z"),
        updated: new Date("2020-01-21T19:27:05Z"),
        rating: "M",
        words: 314960,
        universes: ["Harry Potter", "Naruto"],
        status: "Incomplete",
      },
      {
        id: 5372432,
        title: "Against the Odds",
        author: {
          id: 1470985,
          name: "PolarPanther",
        },
        description:
          "Magic was not the only secret hidden in Harry's ancestry. With nothing more than an old clue and a desperate wish, Harry travels through unfamiliar places and braves unknown danger to find his family.",
        imageUrl: "/image/149683/75/",
        favorites: 7712,
        follows: 8991,
        reviews: 2650,
        genre: ["Family", "Friendship"],
        characters: [["Harry P."], ["Naruto U."]],
        language: "English",
        published: new Date("2009-09-13T00:10:24.000Z"),
        updated: new Date("2019-05-06T04:31:00.000Z"),
        rating: "T",
        words: 178927,
        universes: ["Harry Potter", "Naruto"],
        status: "Incomplete",
      },
      {
        id: 10672002,
        title: "The Biggest Toad in the Puddle",
        author: {
          id: 2221413,
          name: "Tsume Yuki",
        },
        description:
          "In which the Master of Death finds himself reborn and Jiraiya get's confirmation of what he's always known; he has no idea what to do with a kid. Good thing this one came self-sufficient. (MoD and reborn Harry) DISCONTINUED",
        imageUrl: "/image/4657073/75/",
        favorites: 7151,
        follows: 8177,
        reviews: 1134,
        genre: ["Family", "Adventure"],
        characters: [["Harry P."], ["Jiraiya"], ["Team Seven"], ["Team Ten"]],
        language: "English",
        published: new Date("2014-09-05T20:38:58.000Z"),
        updated: new Date("2014-10-14T23:44:14.000Z"),
        rating: "T",
        words: 20034,
        universes: ["Harry Potter", "Naruto"],
        status: "Incomplete",
      },
      {
        id: 8525251,
        title: "Effloresco Secundus",
        author: {
          id: 1605665,
          name: "romanescue",
        },
        description:
          "Harry was never the only person with a penchant for tripping into the most absurd of situations. Reincarnated!Hermione. Somewhat darker than the usual take on Naruto. Political machinations. Character progression. Strong friendship, no romance.",
        imageUrl: "/image/1541607/75/",
        favorites: 7093,
        follows: 8040,
        reviews: 4217,
        genre: ["Drama", "Friendship"],
        characters: [["Hermione G."], ["Sakura H."], ["Team Seven"]],
        language: "English",
        published: new Date("2012-09-15T00:06:27.000Z"),
        updated: new Date("2018-06-15T15:03:58.000Z"),
        rating: "M",
        words: 216750,
        universes: ["Harry Potter", "Naruto"],
        status: "Incomplete",
      },
      {
        id: 7648998,
        title: "A Sage Among Wizards",
        author: {
          id: 2823966,
          name: "Kythorian",
        },
        description:
          "An old and dying Naruto throws his soul forward through time in order to prevent the Juubi's escape upon his death. His soul merges with that of 15 month old Harry Potter in the moment the Killing Curse is reflected. Super!Harry.",
        imageUrl: "/image/2704354/75/",
        favorites: 6218,
        follows: 6958,
        reviews: 3408,
        genre: ["Adventure", "Humor"],
        characters: [["Harry P."]],
        language: "English",
        published: new Date("2011-12-19T01:41:47.000Z"),
        updated: new Date("2013-08-28T11:34:59.000Z"),
        rating: "T",
        words: 74226,
        universes: ["Harry Potter", "Naruto"],
        status: "Incomplete",
      },
      {
        author: {
          id: 714473,
          name: "Mrs.InsaneOne",
        },
        characters: [
          ["Harry P."],
          ["Naruto U."],
          ["Kakashi H."],
          ["Shikaku N."],
        ],
        description:
          "When Naruto returned to Konoha after spending just over two years on the road training under Jiraiya, he never expected to pick up a living shadow with a mind of his own. No Pairings. De-aged!Harry, MOD!Harry, Strong!Harry, Intuitive!Naruto, Strong!Naruto, & Protective!Naruto",
        favorites: 6076,
        follows: 6628,
        genre: ["Drama", "Family"],
        id: 10552343,
        imageUrl: "/image/1459308/75/",
        language: "English",
        published: new Date("2014-07-20T21:06:09.000Z"),
        rating: "T",
        reviews: 2066,
        status: "Incomplete",
        title: "Stubborn Shadow",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2015-12-21T03:54:51.000Z"),
        words: 208235,
      },
      {
        author: {
          id: 8238374,
          name: "Amorphis760",
        },
        characters: [["OC"]],
        description:
          "I was nothing special before I died the first time but when something offers me the chance to live again I take it. Reborn into a world of death I will survive. There will be no mercy and no pity. For there are monsters that roam this world and to survive I might have to become one myself. Elements of the Gamer and X-overs in later chapters.",
        favorites: 5996,
        follows: 6387,
        genre: ["Adventure"],
        id: 12314675,
        imageUrl: "/image/4602707/75/",
        language: "English",
        published: new Date("2017-01-09T04:28:37.000Z"),
        rating: "M",
        reviews: 2486,
        status: "Incomplete",
        title: "The Root of Darkness",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2017-07-05T22:58:39.000Z"),
        words: 246626,
      },
      {
        author: {
          id: 3243738,
          name: "88mph",
        },
        characters: [["Harry P."]],
        description:
          "Harry dies at the end of Deathly Hallows and is reborn as Naruto. Now Harry is on the case of uncovering all the secrets around Naruto and deal with his enemies. Find out how Konoha deals with the Master of Death Ninja-in-training.",
        favorites: 5817,
        follows: 6223,
        genre: ["Supernatural", "Adventure"],
        id: 7404024,
        imageUrl: undefined,
        language: "English",
        published: new Date("2011-09-23T03:12:11.000Z"),
        rating: "M",
        reviews: 1568,
        status: "Incomplete",
        title: "Ninja Who Lived",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2013-11-12T20:48:50.000Z"),
        words: 77566,
      },
      {
        author: {
          id: 1541756,
          name: "ToBetasered",
        },
        characters: [["Harry P."], ["Mikoto U."]],
        description:
          "Uchiha Fukurou was conceived when at the same moment, in another universe, Old Man Potter died.",
        favorites: 5777,
        follows: 5422,
        genre: ["Adventure"],
        id: 7145519,
        imageUrl: "/image/2060860/75/",
        language: "English",
        published: new Date("2011-07-04T20:08:25.000Z"),
        rating: "T",
        reviews: 2314,
        status: "Incomplete",
        title: "Uchiha Fukurou",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2012-05-04T02:12:41.000Z"),
        words: 85861,
      },
      {
        author: {
          id: 3996465,
          name: "Watermelonsmellinfellon",
        },
        characters: [
          ["Harry P.", "Kakashi H."],
          ["Naruto U.", "Sasuke U."],
        ],
        description:
          "Tsume Yuki's, 'Ain't Never Had a Friend Like Me' prompt. MoD Hari is sealed inside a genie bottle and tossed into the Veil. Only the interference of Death stops her from being enslaved. When Naruto comes into possession of the bottle and frees Hari from her prison, she gets attached and decides to help him, changing everything we know. A/N: Har/kashi Naru/Sasu. Deal With It!",
        favorites: 5761,
        follows: 6332,
        genre: ["Adventure", "Romance"],
        id: 11740014,
        imageUrl: "/image/3746467/75/",
        language: "English",
        published: new Date("2016-01-18T17:52:45.000Z"),
        rating: "M",
        reviews: 1935,
        status: "Incomplete",
        title: "Can Your Friends Do This?",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2019-07-10T19:06:36.000Z"),
        words: 323427,
      },
      {
        author: {
          id: 2174929,
          name: "Corruptmonk",
        },
        characters: [["Harry P."], ["Naruto U."]],
        description:
          "After defeating Voldemort and freeing the wizarding world from his clutches, Harry was ostracized and labeled as the new Dark Lord. A belated help from Albus Dumbledore offered him a new chance at life, a new home to call his own, a new world to make a name for himself. Strong-Powerful-Shinobi Wizard Harry, Strong-Naruto, no pairings as of yet.",
        favorites: 5743,
        follows: 5692,
        genre: ["Adventure"],
        id: 8357872,
        imageUrl: "/image/2308046/75/",
        language: "English",
        published: new Date("2012-07-25T18:48:53.000Z"),
        rating: "T",
        reviews: 1896,
        status: "Incomplete",
        title: "Wizard Hidden In The Leaf",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2013-03-18T05:28:23.000Z"),
        words: 134942,
      },
      {
        author: {
          id: 2088474,
          name: "ImmemorialMemory",
        },
        characters: [["Harry P."], ["Naruto U."], ["Sasuke U."], ["Hinata H."]],
        description:
          "The Hyuuga Clan is also known as the All-Seeing Clan. But they didn't need the help of the Byakugan to know that there was something special about their heiress. (Harry is Hyuuga Hinata/Second in my Reincarnation Series)",
        favorites: 5477,
        follows: 6555,
        genre: ["Adventure", "Romance"],
        id: 12579046,
        imageUrl: "/image/5009903/75/",
        language: "English",
        published: new Date("2017-07-19T13:05:26.000Z"),
        rating: "T",
        reviews: 861,
        status: "Incomplete",
        title: "Towards the Sun",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2019-07-20T13:08:40.000Z"),
        words: 33370,
      },
      {
        author: {
          id: 4674022,
          name: "worldtravellingfly",
        },
        characters: [["Harry P.", "Shikaku N."], ["Hedwig"], ["Shikamaru N."]],
        description:
          "Yoshino has died shortly after giving birth to Shikamaru due to an assassination by Iwa. After nearly completing the standard mourning period, Shikaku now must consider marrying again, hounded by fangirls, ambitious kunoichi, and his Clan Elders. Enter a herd of intelligent deer, a confusing Owl Summons Clan, and one world-traveling witch in search of a new purpose. (AU, Fem!Harry)",
        favorites: 5462,
        follows: 2498,
        genre: ["Drama", "Romance"],
        id: 11339805,
        imageUrl: "/image/1210317/75/",
        language: "English",
        published: new Date("2015-06-26T09:12:53.000Z"),
        rating: "T",
        reviews: 284,
        status: "Complete",
        title: "The Owl Princess",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2015-09-27T08:46:15.000Z"),
        words: 22546,
      },
      {
        author: {
          id: 1168221,
          name: "EmLights",
        },
        characters: [
          ["Harry P."],
          ["Naruto U."],
          ["Sasuke U."],
          ["Kakashi H."],
        ],
        description:
          'The final battle has ended and Harry Potter, exhausted and dying, waits patiently to succumb to his injuries so he can finally see his friends and family again. With his notorious luck of getting thrown into difficult situations, Harry instead finds himself shrunk and lost in a new world via the Fates, who may or may not have ulterior motives for this "Next Great Adventure."',
        favorites: 5447,
        follows: 7221,
        genre: ["Adventure", "Family"],
        id: 7511927,
        imageUrl: "/image/4216209/75/",
        language: "English",
        published: new Date("2011-10-31T23:30:55.000Z"),
        rating: "T",
        reviews: 1717,
        status: "Incomplete",
        title: "The Next Great Adventure",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2020-06-10T23:02:17.000Z"),
        words: 91021,
      },
      {
        author: {
          id: 108887,
          name: "Wingwyrm",
        },
        characters: [["Harry P."], ["Naruto U."]],
        description:
          "Harry Potter's animagus form is the Kyuubi no Yōko. And now he's stuck in a little boy named Naruto. So he helps the kid out. And boy is the kid hyperactive. Gen, WIP, AU.",
        favorites: 5430,
        follows: 5953,
        genre: ["Friendship"],
        id: 5852062,
        imageUrl: "/image/1574410/75/",
        language: "English",
        published: new Date("2010-03-29T10:58:20.000Z"),
        rating: "T",
        reviews: 1107,
        status: "Incomplete",
        title: "Multicolour Post Its",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2012-01-21T11:43:53.000Z"),
        words: 22629,
      },
      {
        author: {
          id: 1165626,
          name: "Hermionechan90",
        },
        characters: [["Harry P."], ["Shikaku N."]],
        description:
          "Harriet Potter has to flee from England better yet, she has to vanish from this World. An acquaintance has a solution for the problem but is she really ready for what this entails? Fem Harry Potter",
        favorites: 5359,
        follows: 5989,
        genre: ["Family", "Adventure"],
        id: 10343740,
        imageUrl: "/image/1397152/75/",
        language: "English",
        published: new Date("2014-05-12T19:05:12.000Z"),
        rating: "M",
        reviews: 1439,
        status: "Incomplete",
        title: "Deer tracks",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2016-07-09T16:48:13.000Z"),
        words: 28431,
      },
      {
        author: {
          id: 6223022,
          name: "Baleygr",
        },
        characters: [["Harry P.", "Naruko U."]],
        description:
          "Harry Potter disappeared seven years ago. Now, the Goblet of Fire has summoned him from where he was. Older than he should be, and not amused that he was taken from his wife, he will do what he has to do in order to get home. He may have been forced into this mess, but he'll be damned if he's going to play by their rules.",
        favorites: 5212,
        follows: 6580,
        genre: ["Adventure", "Romance"],
        id: 12584637,
        imageUrl: "/image/3131602/75/",
        language: "English",
        published: new Date("2017-07-24T10:18:47.000Z"),
        rating: "T",
        reviews: 778,
        status: "Incomplete",
        title: "A Ninja Summoned",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2020-01-25T00:06:18.000Z"),
        words: 43960,
      },
      {
        author: {
          id: 912889,
          name: "sakurademonalchemist",
        },
        characters: [["Harry P."], ["Naruto U."]],
        description:
          "The Three tails was tired of being used. Magic didn't want it's savior to grow up in a house where it could die from neglect. And someone needed to give the Fox kid a reason to hope. Magic and chakra combine to create one of the most deadly water users in the Elemental countries and the one who abandoned Haru on that doorstep is going to pay.",
        favorites: 4963,
        follows: 5079,
        genre: ["Humor", "Family"],
        id: 8530656,
        imageUrl: "/image/520244/75/",
        language: "English",
        published: new Date("2012-09-16T18:21:54.000Z"),
        rating: "T",
        reviews: 1112,
        status: "Incomplete",
        title: "Shark in the Leaf",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2013-07-11T20:36:24.000Z"),
        words: 33606,
      },
      {
        author: {
          id: 1238080,
          name: "enchanted nightingale",
        },
        characters: [["Harry P."], ["Teddy L."], ["Kakashi H."]],
        description:
          "Loneliness was not for him, Harry knew that. Then he met Kakashi and he found a solution to his problem. HarryKakashi. SLASH.",
        favorites: 4951,
        follows: 4814,
        genre: ["Romance"],
        id: 6119958,
        imageUrl: "/image/1942838/75/",
        language: "English",
        published: new Date("2010-07-07T20:24:17.000Z"),
        rating: "M",
        reviews: 1842,
        status: "Complete",
        title: "Sneaking Around Konoha",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2021-01-06T17:11:35.000Z"),
        words: 133409,
      },
      {
        author: {
          id: 1318815,
          name: "The Carnivorous Muffin",
        },
        characters: [["Harry P.", "Minato N."]],
        description:
          "On October 10th when the Kyuubi no Kitsune ravages Konoha, Namikaze Minato unwittingly makes a bargain with Death. Years earlier, his life is rewritten when the overpowered, bizarre, and possibly alien Eleanor Lily Potter arrives at Konoha's orphanage and quickly becomes his best friend.",
        favorites: 4933,
        follows: 5232,
        genre: ["Adventure", "Friendship"],
        id: 11666799,
        imageUrl: "/image/3950027/75/",
        language: "English",
        published: new Date("2015-12-13T23:35:30.000Z"),
        rating: "T",
        reviews: 3370,
        status: "Incomplete",
        title: "Minato Namikaze and the Destroyer of Worlds",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2020-10-24T02:46:48.000Z"),
        words: 348576,
      },
      {
        author: {
          id: 2149875,
          name: "White Angel of Auralon",
        },
        characters: [["Harry P."], ["Neville L."], ["Naruto U."]],
        description:
          "Harry Potter is more than a wizard, he's descended from two powerful clans of the Elemental Nations. Thanks to his parents taking precautions he will work on training both sides of his heritage. And people better didn't try to stop him. Will contain some bashing, see summary, no pairings yet.",
        favorites: 4919,
        follows: 5613,
        genre: ["Adventure", "Friendship"],
        id: 9892144,
        imageUrl: "/image/2299043/75/",
        language: "English",
        published: new Date("2013-12-01T23:17:31.000Z"),
        rating: "T",
        reviews: 1779,
        status: "Incomplete",
        title: "Heritage",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2017-06-19T15:46:26.000Z"),
        words: 93644,
      },
      {
        author: {
          id: 714473,
          name: "Mrs.InsaneOne",
        },
        characters: [["Harry P."], ["Naruto U."], ["Kakashi H."], ["Yamato"]],
        description:
          "One man's Greater Good will fall to pieces when his greatest pawn is whisked away as part of the plans his mother set into motion the moment she learned of the dangers her son would face. Pairings TBD. Starts Pre-Hogwarts/Pre-Uchiha Massacre. Shinobi!Harry, Smart!Naruto&Harry, Prankster!Naruto&Harry, Father!Tenzou/Yamato, NotLazy!Kakashi, & Mentor!Kakashi",
        favorites: 4864,
        follows: 5556,
        genre: ["Adventure", "Humor"],
        id: 11146326,
        imageUrl: "/image/3227619/75/",
        language: "English",
        published: new Date("2015-03-29T07:53:17.000Z"),
        rating: "T",
        reviews: 2078,
        status: "Incomplete",
        title: "Twice Blessed Shinobi",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2018-01-22T03:15:04.000Z"),
        words: 278449,
      },
      {
        author: {
          id: 867598,
          name: "Phantom Feline",
        },
        characters: [["Harry P."]],
        description:
          "POLL RESULT; PROFILE Harry thought he would die; had anticipated it, even. So now what will he do in this new world, one without magic? Not to say that there isn't power lurking here... With snakes calling him 'Lord', and everyone else saying 'Abomination', is it any surprise that he's not going to have an easy time settling down? HP AU. Eventual Naruto AU. Slow paced. Dark Themes.",
        favorites: 4852,
        follows: 5542,
        genre: ["Supernatural", "Drama"],
        id: 6953581,
        imageUrl: "/image/1874682/75/",
        language: "English",
        published: new Date("2011-05-01T01:44:15.000Z"),
        rating: "M",
        reviews: 2358,
        status: "Incomplete",
        title: "Continuing the Cycle",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2016-04-09T23:36:58.000Z"),
        words: 133617,
      },
      {
        author: {
          id: 2085016,
          name: "fg7dragon",
        },
        characters: [["Harry P."], ["Luna L."], ["Susan B."], ["Kaguya Ō."]],
        description:
          "Purebloods have always been obsessed with maintaining their bloodlines. What was this based on? What is the origin of these traditions? Or rather WHO? As always Harry finds himself in the oddest situations. But finding himself face to face with the Progenitor of Magic Itself? That's certainly not what he expected when he got out of bed in the morning.",
        favorites: 4504,
        follows: 4796,
        genre: ["Adventure", "Fantasy"],
        id: 11517217,
        imageUrl: "/image/3535728/75/",
        language: "English",
        published: new Date("2015-09-20T18:22:51.000Z"),
        rating: "M",
        reviews: 1762,
        status: "Incomplete",
        title: "The Ōtsutsuki Transmigrant",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2018-01-04T23:25:26.000Z"),
        words: 185144,
      },
      {
        author: {
          id: 802806,
          name: "kirallie",
        },
        characters: [["Harry P.", "Kakashi H."], ["Luna L."], ["Sasuke U."]],
        description:
          "HPNaruto crossover.HarryKakashi eventually. What happens when a certain Wizard finds an unexpected bundle on his doorstep? A shinobi raised as a wizard instead? Totally AU for both although folows HP until Sirius' death.",
        favorites: 4296,
        follows: 4328,
        genre: [],
        id: 2942896,
        imageUrl: "/image/333477/75/",
        language: "English",
        published: new Date("2006-05-17T02:07:23.000Z"),
        rating: "T",
        reviews: 1876,
        status: "Complete",
        title: "Since When Are There Two Potters?",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2020-07-16T03:13:10.000Z"),
        words: 65120,
      },
    ]);
  });

  it("should parse all crossover list", async function () {
    const fragment = await loadTestCase("07-hp-crossovers.html");
    const parsed = await parseStoryList(fragment);

    expect(parsed).toStrictEqual([
      {
        id: 8501689,
        title: "The Havoc side of the Force",
        author: {
          id: 3484707,
          name: "Tsu Doh Nimh",
        },
        description:
          "I have a singularly impressive talent for messing up the plans of very powerful people - both good and evil. Somehow, I'm always just in the right place at exactly the wrong time. What can I say? It's a gift.",
        imageUrl: "/image/2482498/75/",
        favorites: 16505,
        follows: 18711,
        reviews: 7473,
        genre: ["Fantasy", "Mystery"],
        characters: [["Anakin Skywalker"], ["Harry P."]],
        language: "English",
        published: new Date("2012-09-06T12:23:48Z"),
        updated: new Date("2019-08-24T11:56:22Z"),
        rating: "T",
        words: 207600,
        universes: ["Star Wars", "Harry Potter"],
        status: "Incomplete",
      },
      {
        author: {
          id: 2042977,
          name: "cywsaphyre",
        },
        characters: [["Harry P."]],
        description:
          "When Harry finally accepted the fact that he had stopped aging, ten years had passed and he knew it was time to leave. AU.",
        favorites: 15566,
        follows: 7715,
        genre: ["Adventure", "Friendship"],
        id: 8148717,
        imageUrl: "/image/2260423/75/",
        language: "English",
        published: new Date("2012-05-25T07:55:52.000Z"),
        rating: "T",
        reviews: 2895,
        status: "Complete",
        title: "Finding Home",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2013-02-19T02:11:21.000Z"),
        words: 61162,
      },
      {
        author: {
          id: 4404355,
          name: "kathryn518",
        },
        characters: [["Aayla S."], ["Ahsoka T."], ["Harry P."]],
        description:
          "Ahsoka Tano left the Jedi Order, walking away after their betrayal. She did not consider the consequences of what her actions might bring, or the danger she might be in. A chance run in with a single irreverent, and possibly crazy, person in a bar changes the course of fate for an entire galaxy.",
        favorites: 15477,
        follows: 17042,
        genre: ["Adventure", "Romance"],
        id: 11157943,
        imageUrl: "/image/3355417/75/",
        language: "English",
        published: new Date("2015-04-03T04:19:37.000Z"),
        rating: "M",
        reviews: 5732,
        status: "Incomplete",
        title: "I Still Haven't Found What I'm Looking For",
        universes: ["Star Wars", "Harry Potter"],
        updated: new Date("2017-09-18T02:26:01.000Z"),
        words: 344480,
      },
      {
        author: {
          id: 2690239,
          name: "Morta's Priest",
        },
        characters: [["Harry P."]],
        description:
          "The world is breaking. War and technology push on the edge of the unbelievable as S.H.I.E.L.D. desperately tries to keep the peace. Soldier and scientist no longer hold the line alone, as an ancient fire burns alongside them. The last of all wizards.",
        favorites: 15062,
        follows: 16689,
        genre: ["Adventure", "Supernatural"],
        id: 8177168,
        imageUrl: "/image/140244/75/",
        language: "English",
        published: new Date("2012-06-03T02:57:07.000Z"),
        rating: "T",
        reviews: 7404,
        status: "Incomplete",
        title: "Wand and Shield",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2015-07-23T00:42:31.000Z"),
        words: 260787,
      },
      {
        author: {
          id: 2222047,
          name: "AnarchicMuse",
        },
        characters: [["Harry P."], ["Loki"]],
        description:
          "In his several millennia of existence Loki Odinson, God of Mischief and Lies, had been many things; he had been a liar, a warrior, and a trickster, just to name a few, but never before had he been a loving father, he'd never been given the chance. However, the moment the tiny creature was in his arms, he knew he would do anything necessary to keep hold of what was his.",
        favorites: 14982,
        follows: 12770,
        genre: ["Family", "Drama"],
        id: 10216252,
        imageUrl: "/image/2325308/75/",
        language: "English",
        published: new Date("2014-03-25T18:23:30.000Z"),
        rating: "T",
        reviews: 5915,
        status: "Complete",
        title: "The Triumph of These Tired Eyes",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2016-11-01T02:31:36.000Z"),
        words: 334619,
      },
      {
        author: {
          id: 5643202,
          name: "Stargon1",
        },
        characters: [["Harry P."]],
        description:
          "After five years travelling the world, Harry Potter has landed in New York. He figures that there's no better place than the city that never sleeps to settle in and forge a new life. If only the heroes, villains, aliens and spies had received the message. Begins just before the Avengers movie and continues through the MCU. Encompasses MCU movies & TV, some others along the way.",
        favorites: 14657,
        follows: 15783,
        genre: ["Adventure"],
        id: 12307781,
        imageUrl: "/image/4391502/75/",
        language: "English",
        published: new Date("2017-01-04T22:01:41.000Z"),
        rating: "T",
        reviews: 10136,
        status: "Complete",
        title: "Heroes Assemble!",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2020-02-05T19:17:24.000Z"),
        words: 603414,
      },
      {
        author: {
          id: 1298529,
          name: "Clell65619",
        },
        characters: [["Harry P."], ["A. E. Stark/Tony"]],
        description:
          "Harry Potter and the Marvel Universe. 5 year old Harry accompanies the Dursleys on a Business trip to Stark International, where an industrial accident kills all of Harry's living relatives. A very different Harry goes to Hogwarts. Dating, Romance, noship",
        favorites: 13731,
        follows: 16292,
        genre: ["Adventure", "Fantasy"],
        id: 3933832,
        imageUrl: "/image/1959781/75/",
        language: "English",
        published: new Date("2007-12-07T23:27:29.000Z"),
        rating: "T",
        reviews: 6369,
        status: "Incomplete",
        title: "Harry Potter and the Invincible TechnoMage",
        universes: ["Harry Potter", "Ironman"],
        updated: new Date("2018-08-29T04:50:16.000Z"),
        words: 208886,
      },
      {
        author: {
          id: 1537229,
          name: "hctiB-notsoB",
        },
        characters: [["Harry P."], ["Hulk/Bruce B."]],
        description:
          "Gen. \"While on the run, Bruce meets a young man who speaks to the moon. He's probably not quite the sanest friend Bruce could have made, but, well...beggers can't be choosers.\"",
        favorites: 13581,
        follows: 15538,
        genre: ["Friendship"],
        id: 8212843,
        imageUrl: "/image/84386/75/",
        language: "English",
        published: new Date("2012-06-13T08:22:11.000Z"),
        rating: "T",
        reviews: 4915,
        status: "Incomplete",
        title: "I See The Moon",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2015-01-19T04:55:54.000Z"),
        words: 40930,
      },
      {
        author: {
          id: 5291694,
          name: "Steelbadger",
        },
        characters: [["Harry P."]],
        description:
          "The Master of Death is a dangerous title; many would claim to hold a position greater than Death. Harry is pulled to Middle-earth by the Witch King of Angmar in an attempt to bring Morgoth back to Arda. A year later Angmar falls and Harry is freed. What will he do with the eternity granted to him? Story begins 1000 years before LotR. Eventual major canon divergence.",
        favorites: 13132,
        follows: 15716,
        genre: ["Adventure"],
        id: 11115934,
        imageUrl: "/image/1789492/75/",
        language: "English",
        published: new Date("2015-03-15T23:22:05.000Z"),
        rating: "T",
        reviews: 5797,
        status: "Incomplete",
        title: "The Shadow of Angmar",
        universes: ["Harry Potter", "Lord of the Rings"],
        updated: new Date("2020-12-25T08:45:03.000Z"),
        words: 217224,
      },
      {
        author: {
          id: 143877,
          name: "Enterprise1701-d",
        },
        characters: [["Harry P."], ["Hestia"]],
        description:
          "Based on a challenge by Gabriel Herrol. A young Harry Potter is abandoned in new York by the Dursleys. He finds his way onto Olympus and starts squatting in an abandoned temple...",
        favorites: 12670,
        follows: 14880,
        genre: ["Adventure"],
        id: 13274956,
        imageUrl: undefined,
        language: "English",
        published: new Date("2019-05-01T09:00:35.000Z"),
        rating: "T",
        reviews: 5981,
        status: "Incomplete",
        title: "Harry Potter, Squatter",
        universes: ["Harry Potter", "Percy Jackson and the Olympians"],
        updated: new Date("2021-01-31T20:28:49.000Z"),
        words: 372473,
      },
      {
        author: {
          id: 6132825,
          name: "joen1801",
        },
        characters: [],
        description:
          "After the Battle of Hogwarts, Harry Potter decided to travel the world. Twelve years later when a new threat attempts to destroy the progress made in Britain he returns home to deal with the situation. During the fight that puts down the small group of upstarts Harry finds himself in a world of ice and fire",
        favorites: 12237,
        follows: 13445,
        genre: ["Adventure"],
        id: 11132113,
        imageUrl: "/image/3928087/75/",
        language: "English",
        published: new Date("2015-03-22T23:21:26.000Z"),
        rating: "M",
        reviews: 4668,
        status: "Incomplete",
        title: "The Difference One Man Can Make",
        universes: ["Harry Potter", "Game of Thrones"],
        updated: new Date("2017-02-02T05:08:47.000Z"),
        words: 265320,
      },
      {
        author: {
          id: 4785338,
          name: "Vimesenthusiast",
        },
        characters: [["Harry P."], ["J. Grey/Marvel Girl/Phoenix"]],
        description:
          "Rescued from the Negative Zone by the Fantastic Four, Harry Potter discovers he is a mutant and decides to take up the cause of equality between mutants and humans (among other causes). How will a dimensionally displaced Harry Potter, one who is extremely intelligent, proactive and not afraid to get his hands dirty effect the marvel universe? Pairings: Harry/Jean/Ororo/others pos.",
        favorites: 12046,
        follows: 12052,
        genre: ["Adventure", "Romance"],
        id: 9443327,
        imageUrl: "/image/1306748/75/",
        language: "English",
        published: new Date("2013-06-30T20:25:07.000Z"),
        rating: "M",
        reviews: 6711,
        status: "Incomplete",
        title: "A Third Path to the Future",
        universes: ["Harry Potter", "Marvel"],
        updated: new Date("2020-10-30T17:55:16.000Z"),
        words: 1900131,
      },
      {
        author: {
          id: 2554380,
          name: "Lionna",
        },
        characters: [["Harry P."], ["Thor"]],
        description:
          "When Harry lands on Asgard, he doesn't expect to be besieged almost immediately by two gods and a giant wolf. But he's always been the adaptable sort. (No pairing.)",
        favorites: 11522,
        follows: 14214,
        genre: ["Humor", "Supernatural"],
        id: 8310486,
        imageUrl: "/image/293691/75/",
        language: "English",
        published: new Date("2012-07-11T23:20:45.000Z"),
        rating: "T",
        reviews: 5240,
        status: "Incomplete",
        title: "Crestfallen",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2018-05-10T20:28:32.000Z"),
        words: 65278,
      },
      {
        author: {
          id: 7288663,
          name: "SpoonandJohn",
        },
        characters: [["Harry P."], ["Albus D."], ["Itachi U."]],
        description:
          'Petunia performs a bit of accidental magic. It says something about her parenting that Uchiha Itachi is considered a better prospect for raising a child. Young Hari is raised by one of the most infamous nukenin of all time and a cadre of "Uncles" whose cumulative effect is very . . . prominent. And someone had the bright idea to bring him back to England. Merlin help them all.',
        favorites: 11183,
        follows: 11652,
        genre: ["Humor", "Adventure"],
        id: 11634921,
        imageUrl: undefined,
        language: "English",
        published: new Date("2015-11-26T05:56:35.000Z"),
        rating: "M",
        reviews: 8029,
        status: "Incomplete",
        title: "Itachi, Is That A Baby?",
        universes: ["Harry Potter", "Naruto"],
        updated: new Date("2020-01-21T19:27:05.000Z"),
        words: 314960,
      },
      {
        author: {
          id: 912889,
          name: "sakurademonalchemist",
        },
        characters: [["Harry P."], ["Velociraptor"]],
        description:
          "Hagrid wins a dragon egg...only what is inside is no dragon. Harry is the first to make eye contact with the creature inside...and ends up with a most unusual familiar. Watch out Hogwarts...things are about to get prehistoric!",
        favorites: 10345,
        follows: 9777,
        genre: ["Adventure", "Humor"],
        id: 11689576,
        imageUrl: "/image/3681834/75/",
        language: "English",
        published: new Date("2015-12-25T06:41:57.000Z"),
        rating: "T",
        reviews: 3770,
        status: "Incomplete",
        title: "Raptor",
        universes: ["Harry Potter", "Jurassic Park"],
        updated: new Date("2016-03-16T22:04:43.000Z"),
        words: 65937,
      },
      {
        author: {
          id: 3414810,
          name: "savya398",
        },
        characters: [["Harry P."], ["Iron Man/Tony S."]],
        description:
          "After his first year at Hogwarts Harry discovers a startling truth that throws him into an entirely new world. He finds a new family and a new home that drastically changes his life for the better, if not crazier. After all when you're the son of Tony Stark, the one and only Iron Man, life is bound to be interesting.",
        favorites: 10292,
        follows: 12239,
        genre: ["Family"],
        id: 9514290,
        imageUrl: undefined,
        language: "English",
        published: new Date("2013-07-21T19:06:43.000Z"),
        rating: "T",
        reviews: 3023,
        status: "Incomplete",
        title: "My Son the Wizard",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2015-05-10T23:52:58.000Z"),
        words: 171472,
      },
      {
        author: {
          id: 2204901,
          name: "Nimbus Llewelyn",
        },
        characters: [["Harry P."], ["Thor"]],
        description:
          "Once, Thor was James Potter, New Mexico being a refinement of Odin's technique (being murdered didn't do Thor's sanity any favours). After a decade, a mostly reformed Loki restores his memories, introducing Thor's son, Harry, to new family and friends. But soon, ancient secrets emerge along with enemies both old and new as darkness rises. Harry is left with a choice: Fight or Die.",
        favorites: 9513,
        follows: 8185,
        genre: ["Adventure", "Drama"],
        id: 8897431,
        imageUrl: "/image/3745436/75/",
        language: "English",
        published: new Date("2013-01-11T13:26:29.000Z"),
        rating: "T",
        reviews: 8777,
        status: "Complete",
        title: "Child of the Storm",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2016-07-12T17:52:06.000Z"),
        words: 824687,
      },
      {
        author: {
          id: 5241558,
          name: "Noodlehammer",
        },
        characters: [],
        description:
          "It only takes a single disharmonious element to throw off the entire composition. Fifty years before Robert Baratheon was to ascend the Iron Throne, Westeros receives one hell of a bad musician. Harry never did care about any player other than himself.",
        favorites: 9379,
        follows: 9969,
        genre: [],
        id: 13034223,
        imageUrl: "/image/4468045/75/",
        language: "English",
        published: new Date("2018-08-13T20:37:47.000Z"),
        rating: "M",
        reviews: 7203,
        status: "Complete",
        title: "A Discordant Note",
        universes: ["Harry Potter", "A song of Ice and Fire"],
        updated: new Date("2020-09-20T08:20:52.000Z"),
        words: 351549,
      },
      {
        author: {
          id: 3136818,
          name: "plums",
        },
        characters: [["Aayla S.", "Harry P.", "M. Brood", "Shaak Ti"]],
        description:
          "While leading the final charge against a retreating Dark Lord, Harry is thrown through a destabilized Demon Portal, landing on a strange world in a galaxy far far away. Eventual Harry / Multi",
        favorites: 9315,
        follows: 10542,
        genre: ["Adventure", "Fantasy"],
        id: 9068231,
        imageUrl: "/image/2379795/75/",
        language: "English",
        published: new Date("2013-03-04T08:05:55.000Z"),
        rating: "M",
        reviews: 2311,
        status: "Incomplete",
        title: "Last Second Savior",
        universes: ["Star Wars", "Harry Potter"],
        updated: new Date("2016-01-23T20:21:35.000Z"),
        words: 123003,
      },
      {
        author: {
          id: 649528,
          name: "nonjon",
        },
        characters: [["Harry P."], ["River"]],
        description:
          "COMPLETE. Firefly: :Harry Potter crossover Post Serenity. Two years have passed since the secret of the planet Miranda got broadcast across the whole 'verse in 2518. The crew of Serenity finally hires a new pilot, but he's a bit peculiar.",
        favorites: 9062,
        follows: 2872,
        genre: ["Adventure"],
        id: 2857962,
        imageUrl: "/image/1850991/75/",
        language: "English",
        published: new Date("2006-03-23T16:36:37.000Z"),
        rating: "M",
        reviews: 4645,
        status: "Complete",
        title: "Browncoat, Green Eyes",
        universes: ["Harry Potter", "Firefly"],
        updated: new Date("2006-11-13T01:50:32.000Z"),
        words: 298538,
      },
      {
        author: {
          id: 4424268,
          name: "cxjenious",
        },
        characters: [],
        description:
          "He remembers being Harry Potter. He dreams of it. He dreams of the Great Other too, a beast of ice and death with eyes red as blood and an army of dead things. He is the second son of the king, but his fortunes change when secrets rather left in the dark come to light, and Westeros is torn asunder by treachery and ambition. Winter is coming, but magic is might. Very Abandoned",
        favorites: 8993,
        follows: 10121,
        genre: ["Fantasy", "Drama"],
        id: 11098283,
        imageUrl: "/image/1779472/75/",
        language: "English",
        published: new Date("2015-03-08T04:44:44.000Z"),
        rating: "M",
        reviews: 3164,
        status: "Incomplete",
        title: "The Black Prince",
        universes: ["Harry Potter", "Game of Thrones"],
        updated: new Date("2019-01-23T15:32:05.000Z"),
        words: 138771,
      },
      {
        author: {
          id: 2648391,
          name: "Umei no Mai",
        },
        characters: [["Xanxus", "Harry P."], ["Luna L."], ["Varia"]],
        description:
          "When you're a Black, you're a Black and nobody gets to hold all the cards except you. Not a Dark Lord with a grudge, not a Headmaster with a prophecy and certainly not the world's most influential Mafia Family... Dorea is as much a Black as a Potter and she is not about to let anybody walk over her! A Fem!Harry story. Slow Build.",
        favorites: 8609,
        follows: 8409,
        genre: ["Family", "Fantasy"],
        id: 10727911,
        imageUrl: "/image/3752900/75/",
        language: "English",
        published: new Date("2014-10-01T08:58:10.000Z"),
        rating: "T",
        reviews: 18672,
        status: "Incomplete",
        title: "Black Sky",
        universes: ["Harry Potter", "Katekyo Hitman Reborn!"],
        updated: new Date("2020-10-10T08:07:46.000Z"),
        words: 1359813,
      },
      {
        author: {
          id: 1806157,
          name: "Dante 2K-25",
        },
        characters: [["Harry P.", "Wanda M./Scarlet Witch", "OC"]],
        description:
          "After Voldemort's defeat, Harry decides to start over in a new world to find peace. However, the world will not grant him this request as the Earth needs its heroes more than ever and Harry has to answer the call. Monsters, Spies, along with costume heroes will grant him the family he has long search for. If the world doesn't destroy him first. HP/WM (God-Like HP)",
        favorites: 8551,
        follows: 10052,
        genre: ["Adventure", "Supernatural"],
        id: 12366238,
        imageUrl: "/image/4542540/75/",
        language: "English",
        published: new Date("2017-02-14T22:55:21.000Z"),
        rating: "T",
        reviews: 4519,
        status: "Incomplete",
        title: "Avengers: Battleground",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2020-01-13T12:21:22.000Z"),
        words: 250027,
      },
      {
        author: {
          id: 4783217,
          name: "The Homing Pigeon",
        },
        characters: [["Harry P."], ["Hulk/Bruce B."]],
        description:
          "An orphan and an outcast, living two lives that should never have intercepted. However what could happen if a nudge forces these worlds to collide? With a new name and a new father will the Boy-Who-Lived accept what Fate marked him for? A Bruce Banner/Harry Potter father/son relationship. Skip to Chapter 13 for the start of the Avengers.",
        favorites: 8521,
        follows: 7754,
        genre: ["Family"],
        id: 11397437,
        imageUrl: "/image/2922579/75/",
        language: "English",
        published: new Date("2015-07-22T17:32:13.000Z"),
        rating: "T",
        reviews: 3471,
        status: "Complete",
        title: "Fates Be Changed",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2017-07-14T07:03:25.000Z"),
        words: 349121,
      },
      {
        author: {
          id: 2042977,
          name: "cywsaphyre",
        },
        characters: [["Harry P."]],
        description:
          "Life's a lot easier when no one knows you and your only worry is whether or not people in each world speak the same languages you do. Harry can attest to it; he's been jumping for years. He knows how to keep his head down and not get invested. On hindsight, with his track record, Harry supposed it was only a matter of time until he did exactly that.",
        favorites: 8507,
        follows: 9791,
        genre: ["Friendship", "Adventure"],
        id: 8208936,
        imageUrl: "/image/2260423/75/",
        language: "English",
        published: new Date("2012-06-12T04:23:38.000Z"),
        rating: "T",
        reviews: 1931,
        status: "Incomplete",
        title: "Wanderer",
        universes: ["Harry Potter", "Avengers"],
        updated: new Date("2017-08-13T21:19:25.000Z"),
        words: 26309,
      },
    ]);
  });

  it("should parse story list", async function () {
    const fragment = await loadTestCase("09-naruto-stories.html");
    const parsed = await parseStoryList(fragment);

    expect(parsed).toStrictEqual([
      {
        id: 13759614,
        title: "Steps of the Shinobi",
        author: {
          id: 2060107,
          name: "Miqila",
        },
        description:
          "A collection of one shots located in the Naruto/Boruto world, starring various characters. This time, the star is Konohamaru!",
        imageUrl: "/image/5435883/75/",
        favorites: 2,
        follows: 2,
        reviews: 3,
        genre: ["Friendship"],
        characters: [],
        language: "English",
        published: new Date("2020-12-02T15:58:26Z"),
        updated: new Date("2021-02-07T12:34:29Z"),
        rating: "K+",
        words: 7158,
        universes: ["Naruto"],
        status: "Incomplete",
      },
      {
        author: {
          id: 5604202,
          name: "Dewi Hyuuchi-chan",
        },
        characters: [["Hinata H."], ["Sasuke U."]],
        description:
          "Hinata Hyuuga, wanita berusia 30 tahun yang merupakan pegawai biasa menghadapi masalah romansa yang sangat rumit. Pacar yang selama 15 tahun bersama dan berkomitmen untuk menikah ternyata mencintai sahabatnya sendiri. Hingga tragedi dimana ia hamil dan maut menimpanya setelah mengetahui perselingkuhan itu. Hal ajaib terjadi, Hinata bangun di tubuhnya saat berusia 15 tahun.",
        favorites: 0,
        follows: 0,
        genre: ["Romance"],
        id: 13813153,
        imageUrl: "/image/6542634/75/",
        language: "Indonesian",
        published: new Date("2021-02-07T12:25:43.000Z"),
        rating: "T",
        reviews: 0,
        status: "Incomplete",
        title: "Still 30",
        universes: ["Naruto"],
        updated: undefined,
        words: 57,
      },
      {
        author: {
          id: 12513074,
          name: "Ama no Tsuki",
        },
        characters: [["Hidan"], ["Konan"], ["Nagato U."], ["Jashin"]],
        description:
          "After her death, Konan finds herself stranded someplace mysterious. Fortunately, she is surrounded by familiar faces. Unfortunately, none of them have any memories of their previous lives. Why don't they remember? Why does she? Why are some of them even there? And what is happening to her and to them? Shipping & kitties included. Minor inspiration by William James.",
        favorites: 25,
        follows: 22,
        genre: ["Family"],
        id: 13337455,
        imageUrl: undefined,
        language: "English",
        published: new Date("2019-07-14T20:25:16.000Z"),
        rating: "T",
        reviews: 11,
        status: "Incomplete",
        title: "New Life",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T12:23:59.000Z"),
        words: 538543,
      },
      {
        author: {
          id: 6748506,
          name: "Liv-75",
        },
        characters: [["Naruto U."], ["Hinata H."]],
        description:
          "Fearing for the future of her clan and seeing her entire family broke apart, Hinata is set on saving what is left and unify together both sides. Only that means scarifying her most tender desire, but what is the price of love and dreams when it is the future of the Hyugas and probably Konoha that you have in your hands?",
        favorites: 23,
        follows: 44,
        genre: ["Drama", "Romance"],
        id: 13728659,
        imageUrl: "/image/6091359/75/",
        language: "English",
        published: new Date("2020-10-25T20:27:42.000Z"),
        rating: "T",
        reviews: 23,
        status: "Incomplete",
        title: "A cold heart",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T12:15:12.000Z"),
        words: 23975,
      },
      {
        author: {
          id: 6504169,
          name: "11Ava11",
        },
        characters: [["Shikamaru N."], ["Temari"], ["Shikadai N."]],
        description:
          "The night was silent. It was cold and it froze the exposed skin that anyone dared to bare for the night sky. The village was asleep, peace reining over the village. It was silent, but the silence didn't last long. It was in the dead of night when she awoke. But when she awoke, darkness awoke with her. What darkness lies in the shadow of the leaf village?",
        favorites: 32,
        follows: 53,
        genre: ["Romance", "Adventure"],
        id: 12706091,
        imageUrl: "/image/4989266/75/",
        language: "English",
        published: new Date("2017-10-29T20:06:56.000Z"),
        rating: "T",
        reviews: 42,
        status: "Incomplete",
        title: "Lethargic",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T11:46:00.000Z"),
        words: 46101,
      },
      {
        author: {
          id: 2140147,
          name: "Aerlinnn",
        },
        characters: [["Sakura H.", "Sasori"], ["Ino Y."], ["Team Seven"]],
        description:
          "Sakura was six when she first realised that her soulmate was completely unlike that of her classmates. [SasoSaku] [Soulmates AU]",
        favorites: 17,
        follows: 27,
        genre: ["Romance", "Friendship"],
        id: 13807609,
        imageUrl: "/image/6067650/75/",
        language: "English",
        published: new Date("2021-01-31T12:14:39.000Z"),
        rating: "T",
        reviews: 2,
        status: "Complete",
        title: "Dreams of You",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T10:56:34.000Z"),
        words: 8412,
      },
      {
        author: {
          id: 11623865,
          name: "Esellyn",
        },
        characters: [["Kushina U.", "Minato N."], ["Mito U."]],
        description:
          "Kushina always wanted to be Hokage, so Mito decides to train her to be the next Hokage, eventually people start wondering which of the two Uzumaki's are really in charge. While raising Naruto, of course.",
        favorites: 66,
        follows: 92,
        genre: ["Family"],
        id: 13549720,
        imageUrl: "/image/5630829/75/",
        language: "English",
        published: new Date("2020-04-11T23:32:18.000Z"),
        rating: "K+",
        reviews: 10,
        status: "Incomplete",
        title: "Kurama Hates Uzumaki",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T10:44:29.000Z"),
        words: 15461,
      },
      {
        author: {
          id: 14290375,
          name: "Devon1408",
        },
        characters: [
          ["Naruto U."],
          ["Sasuke U."],
          ["Sakura H."],
          ["Kakashi H."],
        ],
        description:
          "Uzumaki m/n, son of Minato and Kushina, older twin of Naruto, Jinchuruki of the yin half of the Kyuubi no Kitsune. All the Uzumaki wanted in life is to find a place where people would accept and not reticule him. he walked to live without regret or fear; he wanted that lifestyle for Naruto, but he knew that his younger brother would be hard to convince to leave.",
        favorites: 2,
        follows: 3,
        genre: ["Angst", "Adventure"],
        id: 13766390,
        imageUrl: "/image/6474108/75/",
        language: "English",
        published: new Date("2020-12-11T13:15:22.000Z"),
        rating: "T",
        reviews: 2,
        status: "Incomplete",
        title: "Whirlpools",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T08:47:41.000Z"),
        words: 26067,
      },
      {
        author: {
          id: 8765842,
          name: "MissUchiha89",
        },
        characters: [["Sakura H."], ["Itachi U."]],
        description:
          "Un equipo especial de Konoha, es enviado a recuperar un importante pergamino robado, tras conseguirlo descubren que dicho robo, fue un señuelo del enemigo para hacerlos perder tiempo. En las sombras, tres reconocidos shinobis trazan sus propios planes que tienen como objetivo a la aldea de la hoja. En medio del conflicto, dos ninjas vuelven a cruzar sus caminos.",
        favorites: 9,
        follows: 16,
        genre: ["Romance"],
        id: 13200328,
        imageUrl: "/image/5894283/75/",
        language: "Spanish",
        published: new Date("2019-02-07T05:46:40.000Z"),
        rating: "K+",
        reviews: 3,
        status: "Incomplete",
        title: "Juego de Máscaras",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T08:29:09.000Z"),
        words: 25252,
      },
      {
        author: {
          id: 12688759,
          name: "UrBoiPedro12",
        },
        characters: [["Naruto U.", "Hinata H."]],
        description:
          '"No matter what you say to me, no matter how hard you try to push me away, I won\'t abandon you and let you do this to yourself" she said firmly, her tone making it clear that it was not up for debate. Even the strongest people can be overwhelmed. When Naruto finally buckles after years of neglect, an unexpected angel appears before him. NaruHina',
        favorites: 117,
        follows: 177,
        genre: ["Romance"],
        id: 13795558,
        imageUrl: undefined,
        language: "English",
        published: new Date("2021-01-15T06:31:45.000Z"),
        rating: "T",
        reviews: 146,
        status: "Incomplete",
        title: "Come Back To Me",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T07:59:15.000Z"),
        words: 33059,
      },
      {
        author: {
          id: 14781126,
          name: "subkap88",
        },
        characters: [
          ["Naruto U."],
          ["Akatsuki"],
          ["Bijū/Tailed Beasts"],
          ["Hagoromo Ō"],
        ],
        description:
          "Naruto was supposed to be a normal child of the fourth Hokage but after his birth something happened that changed his and konoha's future forever.",
        favorites: 4,
        follows: 6,
        genre: ["Supernatural", "Friendship"],
        id: 13813085,
        imageUrl: undefined,
        language: "English",
        published: new Date("2021-02-07T07:53:49.000Z"),
        rating: "T",
        reviews: 1,
        status: "Incomplete",
        title: "Naruto 'Hagoromo' Namikaze",
        universes: ["Naruto"],
        updated: undefined,
        words: 1363,
      },
      {
        author: {
          id: 3653116,
          name: "Withered Pages",
        },
        characters: [["Naruto U."], ["Kabuto Y."], ["OC"]],
        description:
          "It's been a thousand years since the Great Ninja War. The faces on the Hokage Mountain are worn smooth, and no one believes the tales passed down about ninja anymore...until an ancient monster awakens from a self-induced slumber to take over the new defenseless world. Now Minari must follow the scion of an ancient ninja family into the past to relearn what the world forgot.",
        favorites: 2,
        follows: 0,
        genre: ["Drama", "Romance"],
        id: 13798242,
        imageUrl: "/image/6141124/75/",
        language: "English",
        published: new Date("2021-01-18T18:43:10.000Z"),
        rating: "T",
        reviews: 0,
        status: "Incomplete",
        title: "Peace",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T07:45:58.000Z"),
        words: 5767,
      },
      {
        author: {
          id: 2045060,
          name: "xSouh",
        },
        characters: [["Sasuke U.", "Sakura H.", "Naruto U."]],
        description:
          "Sasuke, Sakura y Naruto. Naruto, Sasuke y Sakura. Sakura, Naruto y Sasuke. No importan como los acomoden, ellos eran un equipo, algo más que eso. Siempre juntos. Cadena de Drabbles SasuSakuNaru. Porque hay cosas que no pueden separarse.",
        favorites: 67,
        follows: 74,
        genre: ["Romance"],
        id: 13571421,
        imageUrl: "/image/6241659/75/",
        language: "Spanish",
        published: new Date("2020-05-02T05:13:29.000Z"),
        rating: "K+",
        reviews: 97,
        status: "Complete",
        title: "нυevoѕ para el deѕayυno",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T06:33:51.000Z"),
        words: 16275,
      },
      {
        author: {
          id: 2045060,
          name: "xSouh",
        },
        characters: [["Sasuke U.", "Sakura H.", "Naruto U."]],
        description:
          "Sasuke, Sakura y Naruto. Naruto, Sakura y Sasuke. Sakura, Naruto y Sasuke. Lo habían conseguido. Pero, ¿qué pasa cuando ya hay hijos en la ecuación? Colección de Drabbles. Continuación de Huevos para el Desayuno",
        favorites: 3,
        follows: 8,
        genre: ["Romance", "Humor"],
        id: 13813055,
        imageUrl: "/image/6542430/75/",
        language: "Spanish",
        published: new Date("2021-02-07T06:33:26.000Z"),
        rating: "T",
        reviews: 1,
        status: "Incomplete",
        title: "RENACIMIENTO",
        universes: ["Naruto"],
        updated: undefined,
        words: 582,
      },
      {
        author: {
          id: 8457906,
          name: "KosemSasuSaku",
        },
        characters: [["Naruto U."], ["Sasuke U."], ["Itachi U."], ["Izumi U."]],
        description:
          "Itachi es un semidios que intenta encontrar su lugar en el mundo, e Izumi es una joven de dieciséis años que cruza por error un portal que la lleva al siglo XVI. La joya del paraíso, un objeto capaz de conceder cualquier deseo a dioses y humanos, los llevara a encontrar el amor y sumergirse en un viaje en que aprenderán a donde pertenecen realmente.",
        favorites: 4,
        follows: 5,
        genre: ["Romance", "Adventure"],
        id: 13725068,
        imageUrl: "/image/6412480/75/",
        language: "Spanish",
        published: new Date("2020-10-21T02:34:09.000Z"),
        rating: "T",
        reviews: 15,
        status: "Incomplete",
        title: "Kóraka: La Sombra del Cuervo",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T06:14:53.000Z"),
        words: 95023,
      },
      {
        author: {
          id: 14489845,
          name: "fantasma.infantil.sin.envidia",
        },
        characters: [["Naruto U.", "Sakura H."], ["Kakashi H."], ["OC"]],
        description:
          "El deseo de proteger puede cambiar todas las decisiones que alguien toma. Una chica entra al mundo de Naruto, sin deseo de involucrarse en la trama ni saber nada del sistema ninja, sin embargo termina siendo la cuidadora de Naruto después de la muerte del cuarto Hokage... Kakashi a perdido a todos los integrantes de su equipo y las ultimas promesas que hizo no las pudo cumplir.",
        favorites: 9,
        follows: 8,
        genre: ["Romance", "Drama"],
        id: 13741114,
        imageUrl: "/image/6434566/75/",
        language: "Spanish",
        published: new Date("2020-11-08T00:58:30.000Z"),
        rating: "K",
        reviews: 6,
        status: "Incomplete",
        title: "Proteger (Kakashi x lectora)",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T06:11:06.000Z"),
        words: 45327,
      },
      {
        author: {
          id: 12471441,
          name: "Tiny.Dncer",
        },
        characters: [
          ["Naruto U."],
          ["Sasuke U."],
          ["Sakura H."],
          ["Team Seven"],
        ],
        description:
          "Sakura has been taking care of her sick civilian mother alone since she was 8. But now a full fledged ninja placed on team 7, she must learn how to stop holding herself back and let her team in, although, that proves challenging when her teammates are the wild and childish Naruto Uzumaki and her cold closed off long time crush, Sasuke Uchiha. (Better explanation inside.)",
        favorites: 164,
        follows: 210,
        genre: ["Adventure", "Romance"],
        id: 13759895,
        imageUrl: undefined,
        language: "English",
        published: new Date("2020-12-03T01:04:39.000Z"),
        rating: "T",
        reviews: 85,
        status: "Incomplete",
        title: "Her Experience",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T04:44:18.000Z"),
        words: 173096,
      },
      {
        author: {
          id: 1497481,
          name: "Modern Age",
        },
        characters: [["Madara U.", "OC"]],
        description:
          "An act of kindness and the meaning of life is what she knows. As a healer, Tsubaki would face her most challenging patient. He was meant to kill as was the law of war. She was meant to save lives as was an act of healing. When their paths cross, a love story of how a man came to take a healer as his wife.",
        favorites: 271,
        follows: 288,
        genre: ["Adventure", "Romance"],
        id: 12743610,
        imageUrl: "/image/6027252/75/",
        language: "English",
        published: new Date("2017-12-01T02:24:51.000Z"),
        rating: "T",
        reviews: 81,
        status: "Complete",
        title: "The Healer",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T04:41:03.000Z"),
        words: 90484,
      },
      {
        author: {
          id: 7302794,
          name: "Alela-chan",
        },
        characters: [["Sasuke U."], ["Sakura H."]],
        description:
          "Desde corta edad, Sasuke supo que sería diferente al resto debido a su mudez. Resentido con lo que le tocó sobrellevar, perdió toda motivación en seguir de pie ante el mundo. Sin embargo, nunca imaginó que Sakura, que apareció como torbellino de inexplicables emociones, llegaría a alumbrar sus días desolados, y sobre todo, que se volvería un bálsamo en su propia tormenta.",
        favorites: 55,
        follows: 66,
        genre: ["Drama", "Romance"],
        id: 13145351,
        imageUrl: "/image/6092291/75/",
        language: "Spanish",
        published: new Date("2018-12-12T16:24:10.000Z"),
        rating: "T",
        reviews: 86,
        status: "Incomplete",
        title: "El Sonido del Silencio",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T04:12:04.000Z"),
        words: 212442,
      },
      {
        author: {
          id: 9108709,
          name: "StrangerOutsider",
        },
        characters: [["Obito U.", "Kakashi H."]],
        description:
          "Con su mente constantemente llena de los recuerdos de un mundo diferente: uno lleno de guerras, sangre y muerte. Obito, estudiando el rostro sonrosado de su nuevo bebe, piensa que después de tanto sufrimiento; el largo camino por el que tuvo que arrastrarse para llegar hasta aquí al final valió la pena. Sobretodo cuando es testigo de la lagrima que escapa de la mascara de Kakashi.",
        favorites: 9,
        follows: 11,
        genre: ["Drama"],
        id: 12941450,
        imageUrl: "/image/5303389/75/",
        language: "Spanish",
        published: new Date("2018-05-19T23:01:42.000Z"),
        rating: "K+",
        reviews: 4,
        status: "Incomplete",
        title: "La Historia de otro Ninja que deseaba ser Hokage",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T03:52:18.000Z"),
        words: 7181,
      },
      {
        author: {
          id: 13549290,
          name: "Kuruf",
        },
        characters: [["Hinata H."], ["Shino A."]],
        description:
          "En esa tarde de otoño, en que las cadenas se rompieron, el viento frio anunciaba, que un nuevo camino aparecía. La pequeña luciérnaga necesitaba volver a brillar, y buscar su propio lugar para iluminar; y él buscaba alcanzar, aquella pequeña luz que no podía tocar.",
        favorites: 2,
        follows: 4,
        genre: ["Romance", "Drama"],
        id: 13801527,
        imageUrl: undefined,
        language: "Spanish",
        published: new Date("2021-01-23T02:11:24.000Z"),
        rating: "K+",
        reviews: 3,
        status: "Incomplete",
        title: "Luciérnagas",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T03:27:06.000Z"),
        words: 28942,
      },
      {
        author: {
          id: 4339541,
          name: "N. Owens",
        },
        characters: [["Sasuke U.", "Hinata H."], ["Naruto U."], ["Sakura H."]],
        description:
          "Lembre-se que as noites foram feitas especialmente para dizer coisas que não se pode dizer no dia seguinte.",
        favorites: 29,
        follows: 30,
        genre: ["Romance", "Drama"],
        id: 10296487,
        imageUrl: "/image/2801615/75/",
        language: "Portuguese",
        published: new Date("2014-04-24T20:10:28.000Z"),
        rating: "T",
        reviews: 18,
        status: "Incomplete",
        title: "Do I Wanna Know?",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T02:58:16.000Z"),
        words: 8047,
      },
      {
        author: {
          id: 891408,
          name: "Hikari Yagami de Takaishi",
        },
        characters: [["Shikamaru N.", "Temari"], ["Shikadai N."]],
        description:
          "One-shot collection. Mainly ShikaTema, with some Sand Siblings and Nara Family interaction.",
        favorites: 5,
        follows: 4,
        genre: ["Family"],
        id: 13795485,
        imageUrl: "/image/1877833/75/",
        language: "English",
        published: new Date("2021-01-15T01:12:53.000Z"),
        rating: "K",
        reviews: 0,
        status: "Incomplete",
        title: "Em Família (In Family)",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T02:11:29.000Z"),
        words: 3195,
      },
      {
        author: {
          id: 891408,
          name: "Hikari Yagami de Takaishi",
        },
        characters: [["Shikamaru N.", "Temari"], ["Shikadai N."]],
        description:
          "Coleção de one-shots, drabbles e afins. Shikatema, Sand Siblings / Irmãos da Areia, Nara family / Clã Nara. Histórias independentes entre si, e podem ser lidas individualmente. Já postada em outra plataforma, repostando aqui.",
        favorites: 2,
        follows: 4,
        genre: ["Family"],
        id: 13794350,
        imageUrl: "/image/1877833/75/",
        language: "Portuguese",
        published: new Date("2021-01-13T15:12:02.000Z"),
        rating: "K",
        reviews: 0,
        status: "Incomplete",
        title: "Em Família",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T02:10:45.000Z"),
        words: 8158,
      },
      {
        author: {
          id: 6312692,
          name: "emilyzombies",
        },
        characters: [
          ["Naruto U."],
          ["Kakashi H."],
          ["Genma S."],
          ["Minato N."],
        ],
        description:
          "I had been summoned by Lord Third for another mission. Only just getting back from a 2-week long mission with Genma and the others, I felt like I deserve a break. Apparently, Lord Third and I did not think the same way. It had been like this for a few years now since I started to get more annoyed in not being able to tell Naruto the truth. He would send me away on long mission",
        favorites: 16,
        follows: 25,
        genre: ["Romance", "Hurt", "Comfort"],
        id: 13763214,
        imageUrl: "/image/6469391/75/",
        language: "English",
        published: new Date("2020-12-07T04:50:13.000Z"),
        rating: "T",
        reviews: 13,
        status: "Incomplete",
        title: "The Other Namikaze",
        universes: ["Naruto"],
        updated: new Date("2021-02-07T02:03:36.000Z"),
        words: 24873,
      },
    ]);
  });
});
